YCMD:changelogs(playerid, params[], help)
{
    Dialog_Show(playerid, "ChangeLogs", DIALOG_STYLE_TABLIST_HEADERS, ""Nexston"Nexston Roleplay "WHITE"- Change Logs", 
    "Tanggal\tStatus\n\
    26/07/2025\t"GREEN"(NEW)\n\
    24/07/2025\t"GRAY"(OLD)\n\
    23/07/2025\t"GRAY"(OLD)\n\
    22/07/2025\t"GRAY"(OLD)\n\
    21/07/2025\t"GRAY"(OLD)\n\
    17/07/2025\t"GRAY"(OLD)\n\
    16/07/2025\t"GRAY"(OLD)\n\
    15/07/2025\t"GRAY"(OLD)\n\
    12/07/2025\t"GRAY"(OLD)\n\
    11/07/2025\t"GRAY"(OLD)", "Open", "Batal");
    return 1;
}