//#include "inventory_old"
#include "core/anticheat/anticheat"
#include "core/fivem_notify/notify_fivem"
#include "core/gun/gun_functions"
#include "core/user-interface/ui"
#include "core/fivem_notify/notify_functions"
#include "core/fivem_notify/SHOWITEMBOX"
//#include "core/salary/salary"
#include "core/phone_system/phone"
#include "core/inventory/inventory"
#include "core/systems/systems_functions"
#include "core/systems/systems_lockpick"
#include "core/systems/systems_dadu"
#include "core/stuff/stuff_functions"
#include "core/robbery_static/robbery_static"
#include "core/voice/voice"
#include "core/invoice/invoice"
#include "core/family/family"
#include "core/JDM/jdm"
#include "core/Marga/marga"
#include "core/modshop/modshop"
#include "core/name_tag/nametag"
#include "core/dynamic/dynamic"
#include "core/casino/casino"
//#include "core/changelogs/changelogs"
#include "core/avTreasure/avTreasure"
#include "core/factions/factions"

#include "core/donator/donator"

//drone
#include "core/drone/drone"

//cctv
#include "core/cctv/cctv"

//couple
#include "core/couple/couple_define"
#include "core/couple/couple_core"
#include "core/couple/couple_cmd" 
#include "core/couple/couple_dialog"
#include "core/couple/couple_hook"  


#include "core/gym/gym"

#include "core/toys/toys"
#include "core/clothes/clothes"
#include "core/systems/systems_clothesshop"

#include "core/systems/systems_antirk"
#include "core/systems/systems_billiard"
#include "core/systems/systems_gacha"
// #include "core/systems/systems_ainpc"

#include "core/activity/activity"
#include "core/systems/systems_mselection"
#include "core/vehicles/vehicles"
#include "core/jobs/jobs"
#include "core/event/event"

#include "core/ask/ask"
#include "core/report/report"

#include "core/anims/anims"
#include "core/systems\systems_dialogs"

#include "core/carsteal/carsteal"

#include "core/dealer_showroom/dealer_showroom"

#include "core/death_system/death_functions"

#include "core/systems\systems_natives"

#include "core/timers/timers"

#include "core/account/account"

#include "core/admin/admin"

#include "core/cmds/cmds"

#include "core/crafting/crafting_functions"
#include "core/damagelog/damagelog"

#include "core/fuel_system/fuel_functions"
//#include "core/gangzone/gangzone"

//#include "core/discord/discord"
#include "core/toll/toll"

#include "core/stall/stall"

#include "core/earthquake/earthquake"

#include "core/balloon/balloon"
#include "core/taser/taser"
#include "core/beanbag/beanbag"
#include "core/tackle/tackle"
#include "core/fader/fader"
#include "core/phone_system/sosial_media/vehicle/vehiclelist"