new Text:MenuRestoPringSewu[43],
    Text:MenuRestoSriMersing[43];

CreateMenuRestoPringSewuTD()
{
    MenuRestoPringSewu[0] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[0], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[0], 1);
    TextDrawColor(MenuRestoPringSewu[0], 0);
    TextDrawSetShadow(MenuRestoPringSewu[0], 0);
    TextDrawSetOutline(MenuRestoPringSewu[0], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[0], 150);
    TextDrawFont(MenuRestoPringSewu[0], 1);
    TextDrawSetProportional(MenuRestoPringSewu[0], 1);

    MenuRestoPringSewu[1] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[1], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[1], 1);
    TextDrawColor(MenuRestoPringSewu[1], 0);
    TextDrawSetShadow(MenuRestoPringSewu[1], 0);
    TextDrawSetOutline(MenuRestoPringSewu[1], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[1], 150);
    TextDrawFont(MenuRestoPringSewu[1], 1);
    TextDrawSetProportional(MenuRestoPringSewu[1], 1);

    MenuRestoPringSewu[2] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[2], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[2], 1);
    TextDrawColor(MenuRestoPringSewu[2], 0);
    TextDrawSetShadow(MenuRestoPringSewu[2], 0);
    TextDrawSetOutline(MenuRestoPringSewu[2], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[2], 150);
    TextDrawFont(MenuRestoPringSewu[2], 1);
    TextDrawSetProportional(MenuRestoPringSewu[2], 1);

    MenuRestoPringSewu[3] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[3], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[3], 1);
    TextDrawColor(MenuRestoPringSewu[3], 0);
    TextDrawSetShadow(MenuRestoPringSewu[3], 0);
    TextDrawSetOutline(MenuRestoPringSewu[3], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[3], 150);
    TextDrawFont(MenuRestoPringSewu[3], 1);
    TextDrawSetProportional(MenuRestoPringSewu[3], 1);

    MenuRestoPringSewu[4] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[4], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[4], 1);
    TextDrawColor(MenuRestoPringSewu[4], 0);
    TextDrawSetShadow(MenuRestoPringSewu[4], 0);
    TextDrawSetOutline(MenuRestoPringSewu[4], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[4], 150);
    TextDrawFont(MenuRestoPringSewu[4], 1);
    TextDrawSetProportional(MenuRestoPringSewu[4], 1);

    MenuRestoPringSewu[5] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[5], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[5], 1);
    TextDrawColor(MenuRestoPringSewu[5], 0);
    TextDrawSetShadow(MenuRestoPringSewu[5], 0);
    TextDrawSetOutline(MenuRestoPringSewu[5], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[5], 150);
    TextDrawFont(MenuRestoPringSewu[5], 1);
    TextDrawSetProportional(MenuRestoPringSewu[5], 1);

    MenuRestoPringSewu[6] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[6], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[6], 1);
    TextDrawColor(MenuRestoPringSewu[6], 0);
    TextDrawSetShadow(MenuRestoPringSewu[6], 0);
    TextDrawSetOutline(MenuRestoPringSewu[6], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[6], 150);
    TextDrawFont(MenuRestoPringSewu[6], 1);
    TextDrawSetProportional(MenuRestoPringSewu[6], 1);

    MenuRestoPringSewu[7] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[7], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[7], 1);
    TextDrawColor(MenuRestoPringSewu[7], 0);
    TextDrawSetShadow(MenuRestoPringSewu[7], 0);
    TextDrawSetOutline(MenuRestoPringSewu[7], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[7], 150);
    TextDrawFont(MenuRestoPringSewu[7], 1);
    TextDrawSetProportional(MenuRestoPringSewu[7], 1);

    MenuRestoPringSewu[8] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[8], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[8], 1);
    TextDrawColor(MenuRestoPringSewu[8], 0);
    TextDrawSetShadow(MenuRestoPringSewu[8], 0);
    TextDrawSetOutline(MenuRestoPringSewu[8], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[8], 150);
    TextDrawFont(MenuRestoPringSewu[8], 1);
    TextDrawSetProportional(MenuRestoPringSewu[8], 1);

    MenuRestoPringSewu[9] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[9], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[9], 1);
    TextDrawColor(MenuRestoPringSewu[9], 0);
    TextDrawSetShadow(MenuRestoPringSewu[9], 0);
    TextDrawSetOutline(MenuRestoPringSewu[9], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[9], 150);
    TextDrawFont(MenuRestoPringSewu[9], 1);
    TextDrawSetProportional(MenuRestoPringSewu[9], 1);

    MenuRestoPringSewu[10] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoPringSewu[10], 0.300, 1.500);
    TextDrawAlignment(MenuRestoPringSewu[10], 1);
    TextDrawColor(MenuRestoPringSewu[10], 0);
    TextDrawSetShadow(MenuRestoPringSewu[10], 0);
    TextDrawSetOutline(MenuRestoPringSewu[10], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[10], 150);
    TextDrawFont(MenuRestoPringSewu[10], 1);
    TextDrawSetProportional(MenuRestoPringSewu[10], 1);

    MenuRestoPringSewu[11] = TextDrawCreate(223.000, 108.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[11], 194.000, 3.000);
    TextDrawAlignment(MenuRestoPringSewu[11], 1);
    TextDrawColor(MenuRestoPringSewu[11], -1);
    TextDrawSetShadow(MenuRestoPringSewu[11], 0);
    TextDrawSetOutline(MenuRestoPringSewu[11], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[11], 255);
    TextDrawFont(MenuRestoPringSewu[11], 4);
    TextDrawSetProportional(MenuRestoPringSewu[11], 1);

    MenuRestoPringSewu[12] = TextDrawCreate(298.000, 108.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[12], 41.000, 3.000);
    TextDrawAlignment(MenuRestoPringSewu[12], 1);
    TextDrawColor(MenuRestoPringSewu[12], 852308735);
    TextDrawSetShadow(MenuRestoPringSewu[12], 0);
    TextDrawSetOutline(MenuRestoPringSewu[12], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[12], 255);
    TextDrawFont(MenuRestoPringSewu[12], 4);
    TextDrawSetProportional(MenuRestoPringSewu[12], 1);

    MenuRestoPringSewu[13] = TextDrawCreate(223.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[13], 194.000, 234.000);
    TextDrawAlignment(MenuRestoPringSewu[13], 1);
    TextDrawColor(MenuRestoPringSewu[13], 100);
    TextDrawSetShadow(MenuRestoPringSewu[13], 0);
    TextDrawSetOutline(MenuRestoPringSewu[13], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[13], 255);
    TextDrawFont(MenuRestoPringSewu[13], 4);
    TextDrawSetProportional(MenuRestoPringSewu[13], 1);

    MenuRestoPringSewu[14] = TextDrawCreate(277.000, 87.000, "Menu Restaurant");
    TextDrawLetterSize(MenuRestoPringSewu[14], 0.310, 2.000);
    TextDrawAlignment(MenuRestoPringSewu[14], 1);
    TextDrawColor(MenuRestoPringSewu[14], 255);
    TextDrawSetShadow(MenuRestoPringSewu[14], 0);
    TextDrawSetOutline(MenuRestoPringSewu[14], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[14], 150);
    TextDrawFont(MenuRestoPringSewu[14], 1);
    TextDrawSetProportional(MenuRestoPringSewu[14], 1);

    MenuRestoPringSewu[15] = TextDrawCreate(276.000, 86.000, "Menu Restaurant");
    TextDrawLetterSize(MenuRestoPringSewu[15], 0.310, 2.000);
    TextDrawAlignment(MenuRestoPringSewu[15], 1);
    TextDrawColor(MenuRestoPringSewu[15], 2147418367);
    TextDrawSetShadow(MenuRestoPringSewu[15], 0);
    TextDrawSetOutline(MenuRestoPringSewu[15], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[15], 150);
    TextDrawFont(MenuRestoPringSewu[15], 1);
    TextDrawSetProportional(MenuRestoPringSewu[15], 1);

    MenuRestoPringSewu[16] = TextDrawCreate(223.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[16], 92.000, 17.000);
    TextDrawAlignment(MenuRestoPringSewu[16], 1);
    TextDrawColor(MenuRestoPringSewu[16], 852308735);
    TextDrawSetShadow(MenuRestoPringSewu[16], 0);
    TextDrawSetOutline(MenuRestoPringSewu[16], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[16], 255);
    TextDrawFont(MenuRestoPringSewu[16], 4);
    TextDrawSetProportional(MenuRestoPringSewu[16], 1);

    MenuRestoPringSewu[17] = TextDrawCreate(325.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[17], 92.000, 17.000);
    TextDrawAlignment(MenuRestoPringSewu[17], 1);
    TextDrawColor(MenuRestoPringSewu[17], 852308735);
    TextDrawSetShadow(MenuRestoPringSewu[17], 0);
    TextDrawSetOutline(MenuRestoPringSewu[17], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[17], 255);
    TextDrawFont(MenuRestoPringSewu[17], 4);
    TextDrawSetProportional(MenuRestoPringSewu[17], 1);

    MenuRestoPringSewu[18] = TextDrawCreate(239.000, 118.000, "Paket Kenyang");
    TextDrawLetterSize(MenuRestoPringSewu[18], 0.250, 1.199);
    TextDrawAlignment(MenuRestoPringSewu[18], 1);
    TextDrawColor(MenuRestoPringSewu[18], -1);
    TextDrawSetShadow(MenuRestoPringSewu[18], 0);
    TextDrawSetOutline(MenuRestoPringSewu[18], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[18], 150);
    TextDrawFont(MenuRestoPringSewu[18], 1);
    TextDrawSetProportional(MenuRestoPringSewu[18], 1);

    MenuRestoPringSewu[19] = TextDrawCreate(343.000, 118.000, "Paket Sedang");
    TextDrawLetterSize(MenuRestoPringSewu[19], 0.250, 1.199);
    TextDrawAlignment(MenuRestoPringSewu[19], 1);
    TextDrawColor(MenuRestoPringSewu[19], -1);
    TextDrawSetShadow(MenuRestoPringSewu[19], 0);
    TextDrawSetOutline(MenuRestoPringSewu[19], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[19], 150);
    TextDrawFont(MenuRestoPringSewu[19], 1);
    TextDrawSetProportional(MenuRestoPringSewu[19], 1);

    MenuRestoPringSewu[20] = TextDrawCreate(218.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[20], 2.000, 234.000);
    TextDrawAlignment(MenuRestoPringSewu[20], 1);
    TextDrawColor(MenuRestoPringSewu[20], 100);
    TextDrawSetShadow(MenuRestoPringSewu[20], 0);
    TextDrawSetOutline(MenuRestoPringSewu[20], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[20], 255);
    TextDrawFont(MenuRestoPringSewu[20], 4);
    TextDrawSetProportional(MenuRestoPringSewu[20], 1);

    MenuRestoPringSewu[21] = TextDrawCreate(421.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[21], 2.000, 234.000);
    TextDrawAlignment(MenuRestoPringSewu[21], 1);
    TextDrawColor(MenuRestoPringSewu[21], 100);
    TextDrawSetShadow(MenuRestoPringSewu[21], 0);
    TextDrawSetOutline(MenuRestoPringSewu[21], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[21], 255);
    TextDrawFont(MenuRestoPringSewu[21], 4);
    TextDrawSetProportional(MenuRestoPringSewu[21], 1);

    MenuRestoPringSewu[22] = TextDrawCreate(223.000, 140.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[22], 92.000, 136.000);
    TextDrawAlignment(MenuRestoPringSewu[22], 1);
    TextDrawColor(MenuRestoPringSewu[22], 255);
    TextDrawSetShadow(MenuRestoPringSewu[22], 0);
    TextDrawSetOutline(MenuRestoPringSewu[22], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[22], 255);
    TextDrawFont(MenuRestoPringSewu[22], 4);
    TextDrawSetProportional(MenuRestoPringSewu[22], 1);

    MenuRestoPringSewu[23] = TextDrawCreate(325.000, 140.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[23], 92.000, 136.000);
    TextDrawAlignment(MenuRestoPringSewu[23], 1);
    TextDrawColor(MenuRestoPringSewu[23], 255);
    TextDrawSetShadow(MenuRestoPringSewu[23], 0);
    TextDrawSetOutline(MenuRestoPringSewu[23], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[23], 255);
    TextDrawFont(MenuRestoPringSewu[23], 4);
    TextDrawSetProportional(MenuRestoPringSewu[23], 1);

    MenuRestoPringSewu[24] = TextDrawCreate(227.000, 147.000, "5 Coconut Water");
    TextDrawLetterSize(MenuRestoPringSewu[24], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[24], 1);
    TextDrawColor(MenuRestoPringSewu[24], -1);
    TextDrawSetShadow(MenuRestoPringSewu[24], 0);
    TextDrawSetOutline(MenuRestoPringSewu[24], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[24], 150);
    TextDrawFont(MenuRestoPringSewu[24], 1);
    TextDrawSetProportional(MenuRestoPringSewu[24], 1);

    MenuRestoPringSewu[25] = TextDrawCreate(227.000, 166.000, "5 Chiken BBQ");
    TextDrawLetterSize(MenuRestoPringSewu[25], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[25], 1);
    TextDrawColor(MenuRestoPringSewu[25], -1);
    TextDrawSetShadow(MenuRestoPringSewu[25], 0);
    TextDrawSetOutline(MenuRestoPringSewu[25], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[25], 150);
    TextDrawFont(MenuRestoPringSewu[25], 1);
    TextDrawSetProportional(MenuRestoPringSewu[25], 1);

    MenuRestoPringSewu[26] = TextDrawCreate(329.000, 148.000, "5 Vanilla Milkshake");
    TextDrawLetterSize(MenuRestoPringSewu[26], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[26], 1);
    TextDrawColor(MenuRestoPringSewu[26], -1);
    TextDrawSetShadow(MenuRestoPringSewu[26], 0);
    TextDrawSetOutline(MenuRestoPringSewu[26], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[26], 150);
    TextDrawFont(MenuRestoPringSewu[26], 1);
    TextDrawSetProportional(MenuRestoPringSewu[26], 1);

    MenuRestoPringSewu[27] = TextDrawCreate(329.000, 166.000, "5 Chiken Rice");
    TextDrawLetterSize(MenuRestoPringSewu[27], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[27], 1);
    TextDrawColor(MenuRestoPringSewu[27], -1);
    TextDrawSetShadow(MenuRestoPringSewu[27], 0);
    TextDrawSetOutline(MenuRestoPringSewu[27], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[27], 150);
    TextDrawFont(MenuRestoPringSewu[27], 1);
    TextDrawSetProportional(MenuRestoPringSewu[27], 1);

    MenuRestoPringSewu[28] = TextDrawCreate(227.000, 186.000, "Price: $2,250");
    TextDrawLetterSize(MenuRestoPringSewu[28], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[28], 1);
    TextDrawColor(MenuRestoPringSewu[28], -1);
    TextDrawSetShadow(MenuRestoPringSewu[28], 0);
    TextDrawSetOutline(MenuRestoPringSewu[28], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[28], 150);
    TextDrawFont(MenuRestoPringSewu[28], 1);
    TextDrawSetProportional(MenuRestoPringSewu[28], 1);

    MenuRestoPringSewu[29] = TextDrawCreate(330.000, 186.000, "Price : $2,000");
    TextDrawLetterSize(MenuRestoPringSewu[29], 0.210, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[29], 1);
    TextDrawColor(MenuRestoPringSewu[29], -1);
    TextDrawSetShadow(MenuRestoPringSewu[29], 0);
    TextDrawSetOutline(MenuRestoPringSewu[29], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[29], 150);
    TextDrawFont(MenuRestoPringSewu[29], 1);
    TextDrawSetProportional(MenuRestoPringSewu[29], 1);

    MenuRestoPringSewu[30] = TextDrawCreate(223.000, 286.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoPringSewu[30], 92.000, 64.000);
    TextDrawAlignment(MenuRestoPringSewu[30], 1);
    TextDrawColor(MenuRestoPringSewu[30], 255);
    TextDrawSetShadow(MenuRestoPringSewu[30], 0);
    TextDrawSetOutline(MenuRestoPringSewu[30], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[30], 255);
    TextDrawFont(MenuRestoPringSewu[30], 4);
    TextDrawSetProportional(MenuRestoPringSewu[30], 1);

    MenuRestoPringSewu[31] = TextDrawCreate(227.000, 288.000, "Max pembelian");
    TextDrawLetterSize(MenuRestoPringSewu[31], 0.230, 1.399);
    TextDrawAlignment(MenuRestoPringSewu[31], 1);
    TextDrawColor(MenuRestoPringSewu[31], -1);
    TextDrawSetShadow(MenuRestoPringSewu[31], 0);
    TextDrawSetOutline(MenuRestoPringSewu[31], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[31], 150);
    TextDrawFont(MenuRestoPringSewu[31], 1);
    TextDrawSetProportional(MenuRestoPringSewu[31], 1);

    MenuRestoPringSewu[32] = TextDrawCreate(227.000, 303.000, "warga : 2 paket");
    TextDrawLetterSize(MenuRestoPringSewu[32], 0.170, 1.299);
    TextDrawAlignment(MenuRestoPringSewu[32], 1);
    TextDrawColor(MenuRestoPringSewu[32], -1);
    TextDrawSetShadow(MenuRestoPringSewu[32], 0);
    TextDrawSetOutline(MenuRestoPringSewu[32], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[32], 150);
    TextDrawFont(MenuRestoPringSewu[32], 1);
    TextDrawSetProportional(MenuRestoPringSewu[32], 1);

    MenuRestoPringSewu[33] = TextDrawCreate(227.000, 315.000, "Fraksi : 3 paket");
    TextDrawLetterSize(MenuRestoPringSewu[33], 0.170, 1.299);
    TextDrawAlignment(MenuRestoPringSewu[33], 1);
    TextDrawColor(MenuRestoPringSewu[33], -1);
    TextDrawSetShadow(MenuRestoPringSewu[33], 0);
    TextDrawSetOutline(MenuRestoPringSewu[33], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[33], 150);
    TextDrawFont(MenuRestoPringSewu[33], 1);
    TextDrawSetProportional(MenuRestoPringSewu[33], 1);

    MenuRestoPringSewu[34] = TextDrawCreate(227.000, 328.000, "Note : pembayaran hanya lewat invoice");
    TextDrawLetterSize(MenuRestoPringSewu[34], 0.129, 1.499);
    TextDrawAlignment(MenuRestoPringSewu[34], 1);
    TextDrawColor(MenuRestoPringSewu[34], -1);
    TextDrawSetShadow(MenuRestoPringSewu[34], 0);
    TextDrawSetOutline(MenuRestoPringSewu[34], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[34], 150);
    TextDrawFont(MenuRestoPringSewu[34], 1);
    TextDrawSetProportional(MenuRestoPringSewu[34], 1);

    MenuRestoPringSewu[35] = TextDrawCreate(321.000, 316.000, "LD_BEAT:chit");
    TextDrawTextSize(MenuRestoPringSewu[35], 26.000, 29.000);
    TextDrawAlignment(MenuRestoPringSewu[35], 1);
    TextDrawColor(MenuRestoPringSewu[35], -16776961);
    TextDrawSetShadow(MenuRestoPringSewu[35], 0);
    TextDrawSetOutline(MenuRestoPringSewu[35], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[35], 255);
    TextDrawFont(MenuRestoPringSewu[35], 4);
    TextDrawSetProportional(MenuRestoPringSewu[35], 1);

    MenuRestoPringSewu[36] = TextDrawCreate(387.000, 316.000, "LD_BEAT:chit");
    TextDrawTextSize(MenuRestoPringSewu[36], 26.000, 29.000);
    TextDrawAlignment(MenuRestoPringSewu[36], 1);
    TextDrawColor(MenuRestoPringSewu[36], -16776961);
    TextDrawSetShadow(MenuRestoPringSewu[36], 0);
    TextDrawSetOutline(MenuRestoPringSewu[36], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[36], 255);
    TextDrawFont(MenuRestoPringSewu[36], 4);
    TextDrawSetProportional(MenuRestoPringSewu[36], 1);

    MenuRestoPringSewu[37] = TextDrawCreate(333.000, 321.000, "LD_SPAC:white"); //close button
    TextDrawTextSize(MenuRestoPringSewu[37], 67.000, 19.000);
    TextDrawAlignment(MenuRestoPringSewu[37], 1);
    TextDrawColor(MenuRestoPringSewu[37], -16776961);
    TextDrawSetShadow(MenuRestoPringSewu[37], 0);
    TextDrawSetOutline(MenuRestoPringSewu[37], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[37], 255);
    TextDrawFont(MenuRestoPringSewu[37], 4);
    TextDrawSetProportional(MenuRestoPringSewu[37], 1);
    TextDrawSetSelectable(MenuRestoPringSewu[37], 1);

    MenuRestoPringSewu[38] = TextDrawCreate(357.000, 323.000, "close");
    TextDrawLetterSize(MenuRestoPringSewu[38], 0.270, 1.199);
    TextDrawAlignment(MenuRestoPringSewu[38], 1);
    TextDrawColor(MenuRestoPringSewu[38], -1);
    TextDrawSetShadow(MenuRestoPringSewu[38], 0);
    TextDrawSetOutline(MenuRestoPringSewu[38], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[38], 150);
    TextDrawFont(MenuRestoPringSewu[38], 1);
    TextDrawSetProportional(MenuRestoPringSewu[38], 1);

    MenuRestoPringSewu[39] = TextDrawCreate(199.000, 197.000, "_");
    TextDrawTextSize(MenuRestoPringSewu[39], 97.000, 95.000);
    TextDrawAlignment(MenuRestoPringSewu[39], 1);
    TextDrawColor(MenuRestoPringSewu[39], -1);
    TextDrawSetShadow(MenuRestoPringSewu[39], 0);
    TextDrawSetOutline(MenuRestoPringSewu[39], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[39], 0);
    TextDrawFont(MenuRestoPringSewu[39], 5);
    TextDrawSetProportional(MenuRestoPringSewu[39], 0);
    TextDrawSetPreviewModel(MenuRestoPringSewu[39], 1546);
    TextDrawSetPreviewRot(MenuRestoPringSewu[39], 0.000, 11.000, 304.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoPringSewu[39], 0, 0);

    MenuRestoPringSewu[40] = TextDrawCreate(235.000, 188.000, "_");
    TextDrawTextSize(MenuRestoPringSewu[40], 94.000, 114.000);
    TextDrawAlignment(MenuRestoPringSewu[40], 1);
    TextDrawColor(MenuRestoPringSewu[40], -1);
    TextDrawSetShadow(MenuRestoPringSewu[40], 0);
    TextDrawSetOutline(MenuRestoPringSewu[40], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[40], 0);
    TextDrawFont(MenuRestoPringSewu[40], 5);
    TextDrawSetProportional(MenuRestoPringSewu[40], 0);
    TextDrawSetPreviewModel(MenuRestoPringSewu[40], 2768);
    TextDrawSetPreviewRot(MenuRestoPringSewu[40], -2.000, 22.000, 463.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoPringSewu[40], 0, 0);

    MenuRestoPringSewu[41] = TextDrawCreate(305.000, 187.000, "_");
    TextDrawTextSize(MenuRestoPringSewu[41], 94.000, 114.000);
    TextDrawAlignment(MenuRestoPringSewu[41], 1);
    TextDrawColor(MenuRestoPringSewu[41], -1);
    TextDrawSetShadow(MenuRestoPringSewu[41], 0);
    TextDrawSetOutline(MenuRestoPringSewu[41], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[41], 0);
    TextDrawFont(MenuRestoPringSewu[41], 5);
    TextDrawSetProportional(MenuRestoPringSewu[41], 0);
    TextDrawSetPreviewModel(MenuRestoPringSewu[41], 19835);
    TextDrawSetPreviewRot(MenuRestoPringSewu[41], -2.000, 22.000, 463.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoPringSewu[41], 0, 0);

    MenuRestoPringSewu[42] = TextDrawCreate(336.000, 206.000, "_");
    TextDrawTextSize(MenuRestoPringSewu[42], 94.000, 84.000);
    TextDrawAlignment(MenuRestoPringSewu[42], 1);
    TextDrawColor(MenuRestoPringSewu[42], -1);
    TextDrawSetShadow(MenuRestoPringSewu[42], 0);
    TextDrawSetOutline(MenuRestoPringSewu[42], 0);
    TextDrawBackgroundColor(MenuRestoPringSewu[42], 0);
    TextDrawFont(MenuRestoPringSewu[42], 5);
    TextDrawSetProportional(MenuRestoPringSewu[42], 0);
    TextDrawSetPreviewModel(MenuRestoPringSewu[42], 2804);
    TextDrawSetPreviewRot(MenuRestoPringSewu[42], 282.000, 26.000, 515.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoPringSewu[42], 0, 0);
}

CreateMenuRestoSriMersingTD()
{
    MenuRestoSriMersing[0] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[0], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[0], 1);
    TextDrawColor(MenuRestoSriMersing[0], 0);
    TextDrawSetShadow(MenuRestoSriMersing[0], 0);
    TextDrawSetOutline(MenuRestoSriMersing[0], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[0], 150);
    TextDrawFont(MenuRestoSriMersing[0], 1);
    TextDrawSetProportional(MenuRestoSriMersing[0], 1);

    MenuRestoSriMersing[1] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[1], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[1], 1);
    TextDrawColor(MenuRestoSriMersing[1], 0);
    TextDrawSetShadow(MenuRestoSriMersing[1], 0);
    TextDrawSetOutline(MenuRestoSriMersing[1], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[1], 150);
    TextDrawFont(MenuRestoSriMersing[1], 1);
    TextDrawSetProportional(MenuRestoSriMersing[1], 1);

    MenuRestoSriMersing[2] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[2], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[2], 1);
    TextDrawColor(MenuRestoSriMersing[2], 0);
    TextDrawSetShadow(MenuRestoSriMersing[2], 0);
    TextDrawSetOutline(MenuRestoSriMersing[2], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[2], 150);
    TextDrawFont(MenuRestoSriMersing[2], 1);
    TextDrawSetProportional(MenuRestoSriMersing[2], 1);

    MenuRestoSriMersing[3] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[3], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[3], 1);
    TextDrawColor(MenuRestoSriMersing[3], 0);
    TextDrawSetShadow(MenuRestoSriMersing[3], 0);
    TextDrawSetOutline(MenuRestoSriMersing[3], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[3], 150);
    TextDrawFont(MenuRestoSriMersing[3], 1);
    TextDrawSetProportional(MenuRestoSriMersing[3], 1);

    MenuRestoSriMersing[4] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[4], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[4], 1);
    TextDrawColor(MenuRestoSriMersing[4], 0);
    TextDrawSetShadow(MenuRestoSriMersing[4], 0);
    TextDrawSetOutline(MenuRestoSriMersing[4], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[4], 150);
    TextDrawFont(MenuRestoSriMersing[4], 1);
    TextDrawSetProportional(MenuRestoSriMersing[4], 1);

    MenuRestoSriMersing[5] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[5], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[5], 1);
    TextDrawColor(MenuRestoSriMersing[5], 0);
    TextDrawSetShadow(MenuRestoSriMersing[5], 0);
    TextDrawSetOutline(MenuRestoSriMersing[5], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[5], 150);
    TextDrawFont(MenuRestoSriMersing[5], 1);
    TextDrawSetProportional(MenuRestoSriMersing[5], 1);

    MenuRestoSriMersing[6] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[6], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[6], 1);
    TextDrawColor(MenuRestoSriMersing[6], 0);
    TextDrawSetShadow(MenuRestoSriMersing[6], 0);
    TextDrawSetOutline(MenuRestoSriMersing[6], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[6], 150);
    TextDrawFont(MenuRestoSriMersing[6], 1);
    TextDrawSetProportional(MenuRestoSriMersing[6], 1);

    MenuRestoSriMersing[7] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[7], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[7], 1);
    TextDrawColor(MenuRestoSriMersing[7], 0);
    TextDrawSetShadow(MenuRestoSriMersing[7], 0);
    TextDrawSetOutline(MenuRestoSriMersing[7], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[7], 150);
    TextDrawFont(MenuRestoSriMersing[7], 1);
    TextDrawSetProportional(MenuRestoSriMersing[7], 1);

    MenuRestoSriMersing[8] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[8], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[8], 1);
    TextDrawColor(MenuRestoSriMersing[8], 0);
    TextDrawSetShadow(MenuRestoSriMersing[8], 0);
    TextDrawSetOutline(MenuRestoSriMersing[8], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[8], 150);
    TextDrawFont(MenuRestoSriMersing[8], 1);
    TextDrawSetProportional(MenuRestoSriMersing[8], 1);

    MenuRestoSriMersing[9] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[9], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[9], 1);
    TextDrawColor(MenuRestoSriMersing[9], 0);
    TextDrawSetShadow(MenuRestoSriMersing[9], 0);
    TextDrawSetOutline(MenuRestoSriMersing[9], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[9], 150);
    TextDrawFont(MenuRestoSriMersing[9], 1);
    TextDrawSetProportional(MenuRestoSriMersing[9], 1);

    MenuRestoSriMersing[10] = TextDrawCreate(270.000, 278.000, "/");
    TextDrawLetterSize(MenuRestoSriMersing[10], 0.300, 1.500);
    TextDrawAlignment(MenuRestoSriMersing[10], 1);
    TextDrawColor(MenuRestoSriMersing[10], 0);
    TextDrawSetShadow(MenuRestoSriMersing[10], 0);
    TextDrawSetOutline(MenuRestoSriMersing[10], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[10], 150);
    TextDrawFont(MenuRestoSriMersing[10], 1);
    TextDrawSetProportional(MenuRestoSriMersing[10], 1);

    MenuRestoSriMersing[11] = TextDrawCreate(223.000, 108.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[11], 194.000, 3.000);
    TextDrawAlignment(MenuRestoSriMersing[11], 1);
    TextDrawColor(MenuRestoSriMersing[11], -1);
    TextDrawSetShadow(MenuRestoSriMersing[11], 0);
    TextDrawSetOutline(MenuRestoSriMersing[11], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[11], 255);
    TextDrawFont(MenuRestoSriMersing[11], 4);
    TextDrawSetProportional(MenuRestoSriMersing[11], 1);

    MenuRestoSriMersing[12] = TextDrawCreate(298.000, 108.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[12], 41.000, 3.000);
    TextDrawAlignment(MenuRestoSriMersing[12], 1);
    TextDrawColor(MenuRestoSriMersing[12], 852308735);
    TextDrawSetShadow(MenuRestoSriMersing[12], 0);
    TextDrawSetOutline(MenuRestoSriMersing[12], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[12], 255);
    TextDrawFont(MenuRestoSriMersing[12], 4);
    TextDrawSetProportional(MenuRestoSriMersing[12], 1);

    MenuRestoSriMersing[13] = TextDrawCreate(223.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[13], 194.000, 234.000);
    TextDrawAlignment(MenuRestoSriMersing[13], 1);
    TextDrawColor(MenuRestoSriMersing[13], 100);
    TextDrawSetShadow(MenuRestoSriMersing[13], 0);
    TextDrawSetOutline(MenuRestoSriMersing[13], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[13], 255);
    TextDrawFont(MenuRestoSriMersing[13], 4);
    TextDrawSetProportional(MenuRestoSriMersing[13], 1);

    MenuRestoSriMersing[14] = TextDrawCreate(277.000, 87.000, "Menu Sri Mersing");
    TextDrawLetterSize(MenuRestoSriMersing[14], 0.310, 2.000);
    TextDrawAlignment(MenuRestoSriMersing[14], 1);
    TextDrawColor(MenuRestoSriMersing[14], 255);
    TextDrawSetShadow(MenuRestoSriMersing[14], 0);
    TextDrawSetOutline(MenuRestoSriMersing[14], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[14], 150);
    TextDrawFont(MenuRestoSriMersing[14], 1);
    TextDrawSetProportional(MenuRestoSriMersing[14], 1);

    MenuRestoSriMersing[15] = TextDrawCreate(276.000, 86.000, "Menu Sri Mersing");
    TextDrawLetterSize(MenuRestoSriMersing[15], 0.310, 2.000);
    TextDrawAlignment(MenuRestoSriMersing[15], 1);
    TextDrawColor(MenuRestoSriMersing[15], 2147418367);
    TextDrawSetShadow(MenuRestoSriMersing[15], 0);
    TextDrawSetOutline(MenuRestoSriMersing[15], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[15], 150);
    TextDrawFont(MenuRestoSriMersing[15], 1);
    TextDrawSetProportional(MenuRestoSriMersing[15], 1);

    MenuRestoSriMersing[16] = TextDrawCreate(223.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[16], 92.000, 17.000);
    TextDrawAlignment(MenuRestoSriMersing[16], 1);
    TextDrawColor(MenuRestoSriMersing[16], 852308735);
    TextDrawSetShadow(MenuRestoSriMersing[16], 0);
    TextDrawSetOutline(MenuRestoSriMersing[16], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[16], 255);
    TextDrawFont(MenuRestoSriMersing[16], 4);
    TextDrawSetProportional(MenuRestoSriMersing[16], 1);

    MenuRestoSriMersing[17] = TextDrawCreate(325.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[17], 92.000, 17.000);
    TextDrawAlignment(MenuRestoSriMersing[17], 1);
    TextDrawColor(MenuRestoSriMersing[17], 852308735);
    TextDrawSetShadow(MenuRestoSriMersing[17], 0);
    TextDrawSetOutline(MenuRestoSriMersing[17], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[17], 255);
    TextDrawFont(MenuRestoSriMersing[17], 4);
    TextDrawSetProportional(MenuRestoSriMersing[17], 1);

    MenuRestoSriMersing[18] = TextDrawCreate(239.000, 118.000, "Minang Combo");
    TextDrawLetterSize(MenuRestoSriMersing[18], 0.250, 1.199);
    TextDrawAlignment(MenuRestoSriMersing[18], 1);
    TextDrawColor(MenuRestoSriMersing[18], -1);
    TextDrawSetShadow(MenuRestoSriMersing[18], 0);
    TextDrawSetOutline(MenuRestoSriMersing[18], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[18], 150);
    TextDrawFont(MenuRestoSriMersing[18], 1);
    TextDrawSetProportional(MenuRestoSriMersing[18], 1);

    MenuRestoSriMersing[19] = TextDrawCreate(343.000, 118.000, "Malaya Shine");
    TextDrawLetterSize(MenuRestoSriMersing[19], 0.250, 1.199);
    TextDrawAlignment(MenuRestoSriMersing[19], 1);
    TextDrawColor(MenuRestoSriMersing[19], -1);
    TextDrawSetShadow(MenuRestoSriMersing[19], 0);
    TextDrawSetOutline(MenuRestoSriMersing[19], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[19], 150);
    TextDrawFont(MenuRestoSriMersing[19], 1);
    TextDrawSetProportional(MenuRestoSriMersing[19], 1);

    MenuRestoSriMersing[20] = TextDrawCreate(218.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[20], 2.000, 234.000);
    TextDrawAlignment(MenuRestoSriMersing[20], 1);
    TextDrawColor(MenuRestoSriMersing[20], 100);
    TextDrawSetShadow(MenuRestoSriMersing[20], 0);
    TextDrawSetOutline(MenuRestoSriMersing[20], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[20], 255);
    TextDrawFont(MenuRestoSriMersing[20], 4);
    TextDrawSetProportional(MenuRestoSriMersing[20], 1);

    MenuRestoSriMersing[21] = TextDrawCreate(421.000, 116.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[21], 2.000, 234.000);
    TextDrawAlignment(MenuRestoSriMersing[21], 1);
    TextDrawColor(MenuRestoSriMersing[21], 100);
    TextDrawSetShadow(MenuRestoSriMersing[21], 0);
    TextDrawSetOutline(MenuRestoSriMersing[21], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[21], 255);
    TextDrawFont(MenuRestoSriMersing[21], 4);
    TextDrawSetProportional(MenuRestoSriMersing[21], 1);

    MenuRestoSriMersing[22] = TextDrawCreate(223.000, 140.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[22], 92.000, 136.000);
    TextDrawAlignment(MenuRestoSriMersing[22], 1);
    TextDrawColor(MenuRestoSriMersing[22], 255);
    TextDrawSetShadow(MenuRestoSriMersing[22], 0);
    TextDrawSetOutline(MenuRestoSriMersing[22], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[22], 255);
    TextDrawFont(MenuRestoSriMersing[22], 4);
    TextDrawSetProportional(MenuRestoSriMersing[22], 1);

    MenuRestoSriMersing[23] = TextDrawCreate(325.000, 140.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[23], 92.000, 136.000);
    TextDrawAlignment(MenuRestoSriMersing[23], 1);
    TextDrawColor(MenuRestoSriMersing[23], 255);
    TextDrawSetShadow(MenuRestoSriMersing[23], 0);
    TextDrawSetOutline(MenuRestoSriMersing[23], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[23], 255);
    TextDrawFont(MenuRestoSriMersing[23], 4);
    TextDrawSetProportional(MenuRestoSriMersing[23], 1);

    MenuRestoSriMersing[24] = TextDrawCreate(227.000, 147.000, "5 Jus Timun");
    TextDrawLetterSize(MenuRestoSriMersing[24], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[24], 1);
    TextDrawColor(MenuRestoSriMersing[24], -1);
    TextDrawSetShadow(MenuRestoSriMersing[24], 0);
    TextDrawSetOutline(MenuRestoSriMersing[24], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[24], 150);
    TextDrawFont(MenuRestoSriMersing[24], 1);
    TextDrawSetProportional(MenuRestoSriMersing[24], 1);

    MenuRestoSriMersing[25] = TextDrawCreate(227.000, 166.000, "5 Nasi Padang");
    TextDrawLetterSize(MenuRestoSriMersing[25], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[25], 1);
    TextDrawColor(MenuRestoSriMersing[25], -1);
    TextDrawSetShadow(MenuRestoSriMersing[25], 0);
    TextDrawSetOutline(MenuRestoSriMersing[25], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[25], 150);
    TextDrawFont(MenuRestoSriMersing[25], 1);
    TextDrawSetProportional(MenuRestoSriMersing[25], 1);

    MenuRestoSriMersing[26] = TextDrawCreate(329.000, 148.000, "5 Sirup Selasih");
    TextDrawLetterSize(MenuRestoSriMersing[26], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[26], 1);
    TextDrawColor(MenuRestoSriMersing[26], -1);
    TextDrawSetShadow(MenuRestoSriMersing[26], 0);
    TextDrawSetOutline(MenuRestoSriMersing[26], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[26], 150);
    TextDrawFont(MenuRestoSriMersing[26], 1);
    TextDrawSetProportional(MenuRestoSriMersing[26], 1);

    MenuRestoSriMersing[27] = TextDrawCreate(329.000, 166.000, "5 Roti Jala");
    TextDrawLetterSize(MenuRestoSriMersing[27], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[27], 1);
    TextDrawColor(MenuRestoSriMersing[27], -1);
    TextDrawSetShadow(MenuRestoSriMersing[27], 0);
    TextDrawSetOutline(MenuRestoSriMersing[27], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[27], 150);
    TextDrawFont(MenuRestoSriMersing[27], 1);
    TextDrawSetProportional(MenuRestoSriMersing[27], 1);

    MenuRestoSriMersing[28] = TextDrawCreate(227.000, 186.000, "Price: $1.750");
    TextDrawLetterSize(MenuRestoSriMersing[28], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[28], 1);
    TextDrawColor(MenuRestoSriMersing[28], -1);
    TextDrawSetShadow(MenuRestoSriMersing[28], 0);
    TextDrawSetOutline(MenuRestoSriMersing[28], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[28], 150);
    TextDrawFont(MenuRestoSriMersing[28], 1);
    TextDrawSetProportional(MenuRestoSriMersing[28], 1);

    MenuRestoSriMersing[29] = TextDrawCreate(330.000, 186.000, "Price : $1,500");
    TextDrawLetterSize(MenuRestoSriMersing[29], 0.209, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[29], 1);
    TextDrawColor(MenuRestoSriMersing[29], -1);
    TextDrawSetShadow(MenuRestoSriMersing[29], 0);
    TextDrawSetOutline(MenuRestoSriMersing[29], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[29], 150);
    TextDrawFont(MenuRestoSriMersing[29], 1);
    TextDrawSetProportional(MenuRestoSriMersing[29], 1);

    MenuRestoSriMersing[30] = TextDrawCreate(223.000, 286.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[30], 92.000, 64.000);
    TextDrawAlignment(MenuRestoSriMersing[30], 1);
    TextDrawColor(MenuRestoSriMersing[30], 255);
    TextDrawSetShadow(MenuRestoSriMersing[30], 0);
    TextDrawSetOutline(MenuRestoSriMersing[30], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[30], 255);
    TextDrawFont(MenuRestoSriMersing[30], 4);
    TextDrawSetProportional(MenuRestoSriMersing[30], 1);

    MenuRestoSriMersing[31] = TextDrawCreate(227.000, 288.000, "Max pembelian");
    TextDrawLetterSize(MenuRestoSriMersing[31], 0.230, 1.399);
    TextDrawAlignment(MenuRestoSriMersing[31], 1);
    TextDrawColor(MenuRestoSriMersing[31], -1);
    TextDrawSetShadow(MenuRestoSriMersing[31], 0);
    TextDrawSetOutline(MenuRestoSriMersing[31], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[31], 150);
    TextDrawFont(MenuRestoSriMersing[31], 1);
    TextDrawSetProportional(MenuRestoSriMersing[31], 1);

    MenuRestoSriMersing[32] = TextDrawCreate(227.000, 303.000, "warga : 2 paket");
    TextDrawLetterSize(MenuRestoSriMersing[32], 0.170, 1.299);
    TextDrawAlignment(MenuRestoSriMersing[32], 1);
    TextDrawColor(MenuRestoSriMersing[32], -1);
    TextDrawSetShadow(MenuRestoSriMersing[32], 0);
    TextDrawSetOutline(MenuRestoSriMersing[32], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[32], 150);
    TextDrawFont(MenuRestoSriMersing[32], 1);
    TextDrawSetProportional(MenuRestoSriMersing[32], 1);

    MenuRestoSriMersing[33] = TextDrawCreate(227.000, 315.000, "Fraksi : 3 paket");
    TextDrawLetterSize(MenuRestoSriMersing[33], 0.170, 1.299);
    TextDrawAlignment(MenuRestoSriMersing[33], 1);
    TextDrawColor(MenuRestoSriMersing[33], -1);
    TextDrawSetShadow(MenuRestoSriMersing[33], 0);
    TextDrawSetOutline(MenuRestoSriMersing[33], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[33], 150);
    TextDrawFont(MenuRestoSriMersing[33], 1);
    TextDrawSetProportional(MenuRestoSriMersing[33], 1);

    MenuRestoSriMersing[34] = TextDrawCreate(227.000, 328.000, "Note : pembayaran hanya lewat invoice");
    TextDrawLetterSize(MenuRestoSriMersing[34], 0.128, 1.498);
    TextDrawAlignment(MenuRestoSriMersing[34], 1);
    TextDrawColor(MenuRestoSriMersing[34], -1);
    TextDrawSetShadow(MenuRestoSriMersing[34], 0);
    TextDrawSetOutline(MenuRestoSriMersing[34], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[34], 150);
    TextDrawFont(MenuRestoSriMersing[34], 1);
    TextDrawSetProportional(MenuRestoSriMersing[34], 1);

    MenuRestoSriMersing[35] = TextDrawCreate(321.000, 316.000, "LD_BEAT:chit");
    TextDrawTextSize(MenuRestoSriMersing[35], 26.000, 29.000);
    TextDrawAlignment(MenuRestoSriMersing[35], 1);
    TextDrawColor(MenuRestoSriMersing[35], -16776961);
    TextDrawSetShadow(MenuRestoSriMersing[35], 0);
    TextDrawSetOutline(MenuRestoSriMersing[35], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[35], 255);
    TextDrawFont(MenuRestoSriMersing[35], 4);
    TextDrawSetProportional(MenuRestoSriMersing[35], 1);

    MenuRestoSriMersing[36] = TextDrawCreate(387.000, 316.000, "LD_BEAT:chit");
    TextDrawTextSize(MenuRestoSriMersing[36], 26.000, 29.000);
    TextDrawAlignment(MenuRestoSriMersing[36], 1);
    TextDrawColor(MenuRestoSriMersing[36], -16776961);
    TextDrawSetShadow(MenuRestoSriMersing[36], 0);
    TextDrawSetOutline(MenuRestoSriMersing[36], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[36], 255);
    TextDrawFont(MenuRestoSriMersing[36], 4);
    TextDrawSetProportional(MenuRestoSriMersing[36], 1);

    MenuRestoSriMersing[37] = TextDrawCreate(333.000, 321.000, "LD_SPAC:white");
    TextDrawTextSize(MenuRestoSriMersing[37], 67.000, 19.000);
    TextDrawAlignment(MenuRestoSriMersing[37], 1);
    TextDrawColor(MenuRestoSriMersing[37], -16776961);
    TextDrawSetShadow(MenuRestoSriMersing[37], 0);
    TextDrawSetOutline(MenuRestoSriMersing[37], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[37], 255);
    TextDrawFont(MenuRestoSriMersing[37], 4);
    TextDrawSetProportional(MenuRestoSriMersing[37], 1);
    TextDrawSetSelectable(MenuRestoSriMersing[37], 1);

    MenuRestoSriMersing[38] = TextDrawCreate(357.000, 323.000, "close");
    TextDrawLetterSize(MenuRestoSriMersing[38], 0.270, 1.199);
    TextDrawAlignment(MenuRestoSriMersing[38], 1);
    TextDrawColor(MenuRestoSriMersing[38], -1);
    TextDrawSetShadow(MenuRestoSriMersing[38], 0);
    TextDrawSetOutline(MenuRestoSriMersing[38], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[38], 150);
    TextDrawFont(MenuRestoSriMersing[38], 1);
    TextDrawSetProportional(MenuRestoSriMersing[38], 1);

    MenuRestoSriMersing[39] = TextDrawCreate(199.000, 197.000, "_");
    TextDrawTextSize(MenuRestoSriMersing[39], 97.000, 95.000);
    TextDrawAlignment(MenuRestoSriMersing[39], 1);
    TextDrawColor(MenuRestoSriMersing[39], -1);
    TextDrawSetShadow(MenuRestoSriMersing[39], 0);
    TextDrawSetOutline(MenuRestoSriMersing[39], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[39], 0);
    TextDrawFont(MenuRestoSriMersing[39], 5);
    TextDrawSetProportional(MenuRestoSriMersing[39], 0);
    TextDrawSetPreviewModel(MenuRestoSriMersing[39], 1546);
    TextDrawSetPreviewRot(MenuRestoSriMersing[39], 0.000, 11.000, 304.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoSriMersing[39], 0, 0);

    MenuRestoSriMersing[40] = TextDrawCreate(235.000, 188.000, "_");
    TextDrawTextSize(MenuRestoSriMersing[40], 94.000, 114.000);
    TextDrawAlignment(MenuRestoSriMersing[40], 1);
    TextDrawColor(MenuRestoSriMersing[40], -1);
    TextDrawSetShadow(MenuRestoSriMersing[40], 0);
    TextDrawSetOutline(MenuRestoSriMersing[40], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[40], 0);
    TextDrawFont(MenuRestoSriMersing[40], 5);
    TextDrawSetProportional(MenuRestoSriMersing[40], 0);
    TextDrawSetPreviewModel(MenuRestoSriMersing[40], 2768);
    TextDrawSetPreviewRot(MenuRestoSriMersing[40], -2.000, 22.000, 463.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoSriMersing[40], 0, 0);

    MenuRestoSriMersing[41] = TextDrawCreate(305.000, 187.000, "_");
    TextDrawTextSize(MenuRestoSriMersing[41], 94.000, 114.000);
    TextDrawAlignment(MenuRestoSriMersing[41], 1);
    TextDrawColor(MenuRestoSriMersing[41], -1);
    TextDrawSetShadow(MenuRestoSriMersing[41], 0);
    TextDrawSetOutline(MenuRestoSriMersing[41], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[41], 0);
    TextDrawFont(MenuRestoSriMersing[41], 5);
    TextDrawSetProportional(MenuRestoSriMersing[41], 0);
    TextDrawSetPreviewModel(MenuRestoSriMersing[41], 19835);
    TextDrawSetPreviewRot(MenuRestoSriMersing[41], -2.000, 22.000, 463.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoSriMersing[41], 0, 0);

    MenuRestoSriMersing[42] = TextDrawCreate(336.000, 206.000, "_");
    TextDrawTextSize(MenuRestoSriMersing[42], 94.000, 84.000);
    TextDrawAlignment(MenuRestoSriMersing[42], 1);
    TextDrawColor(MenuRestoSriMersing[42], -1);
    TextDrawSetShadow(MenuRestoSriMersing[42], 0);
    TextDrawSetOutline(MenuRestoSriMersing[42], 0);
    TextDrawBackgroundColor(MenuRestoSriMersing[42], 0);
    TextDrawFont(MenuRestoSriMersing[42], 5);
    TextDrawSetProportional(MenuRestoSriMersing[42], 0);
    TextDrawSetPreviewModel(MenuRestoSriMersing[42], 2804);
    TextDrawSetPreviewRot(MenuRestoSriMersing[42], 282.000, 26.000, 515.000, 1.000);
    TextDrawSetPreviewVehCol(MenuRestoSriMersing[42], 0, 0);
}

ShowMenuRestoPringSewuTD(playerid)
{
	for(new x; x < 43; x++)
    {
    	TextDrawShowForPlayer(playerid, MenuRestoPringSewu[x]);
	}
    HideHBETD(playerid);
	HideRadioVoiceInfoTD(playerid);
    HideWargaBaruTD(playerid);
    SelectTextDraw(playerid, Y_Nexston);

}

HideMenuRestoPringSewuTD(playerid)
{
    for(new x; x < 43; x++)
    {
        TextDrawHideForPlayer(playerid, MenuRestoPringSewu[x]);
    }
    ShowHBETD(playerid);
	ShowRadioVoiceInfoTD(playerid);
    ShowWargaBaruTD(playerid);
    CancelSelectTextDraw(playerid);
}

ShowMenuRestoSriMersingTD(playerid)
{
	for(new i; i < 43; i++)
    {
    	TextDrawShowForPlayer(playerid, MenuRestoSriMersing[i]);
	}
    HideHBETD(playerid);
	HideRadioVoiceInfoTD(playerid);
    HideWargaBaruTD(playerid);
    SelectTextDraw(playerid, Y_Nexston);

}

HideMenuRestoSriMersingTD(playerid)
{
    for(new i; i < 43; i++)
    {
        TextDrawHideForPlayer(playerid, MenuRestoSriMersing[i]);
    }
    ShowHBETD(playerid);
	ShowRadioVoiceInfoTD(playerid);
    ShowWargaBaruTD(playerid);
    CancelSelectTextDraw(playerid);
}