new Text:SpawnSelectorTD[10];

CreateSpawnSelectorTD()
{
    SpawnSelectorTD[0] = TextDrawCreate(399.000, 134.000, "LD_BUM:blkdot");
    TextDrawTextSize(SpawnSelectorTD[0], 100.000, 19.000);
    TextDrawAlignment(SpawnSelectorTD[0], 1);
    TextDrawColor(SpawnSelectorTD[0], -12582657);
    TextDrawSetShadow(SpawnSelectorTD[0], 0);
    TextDrawSetOutline(SpawnSelectorTD[0], 0);
    TextDrawBackgroundColor(SpawnSelectorTD[0], 255);
    TextDrawFont(SpawnSelectorTD[0], 4);
    TextDrawSetProportional(SpawnSelectorTD[0], 1);

    SpawnSelectorTD[1] = TextDrawCreate(399.000, 157.500, "LD_BUM:blkdot");
    TextDrawTextSize(SpawnSelectorTD[1], 100.000, 19.000);
    TextDrawAlignment(SpawnSelectorTD[1], 1);
    TextDrawColor(SpawnSelectorTD[1], 454894591);
    TextDrawSetShadow(SpawnSelectorTD[1], 0);
    TextDrawSetOutline(SpawnSelectorTD[1], 0);
    TextDrawBackgroundColor(SpawnSelectorTD[1], 255);
    TextDrawFont(SpawnSelectorTD[1], 4);
    TextDrawSetProportional(SpawnSelectorTD[1], 1);
    TextDrawSetSelectable(SpawnSelectorTD[1], 1);

    SpawnSelectorTD[2] = TextDrawCreate(399.000, 181.000, "LD_BUM:blkdot");
    TextDrawTextSize(SpawnSelectorTD[2], 100.000, 19.000);
    TextDrawAlignment(SpawnSelectorTD[2], 1);
    TextDrawColor(SpawnSelectorTD[2], 454894591);
    TextDrawSetShadow(SpawnSelectorTD[2], 0);
    TextDrawSetOutline(SpawnSelectorTD[2], 0);
    TextDrawBackgroundColor(SpawnSelectorTD[2], 255);
    TextDrawFont(SpawnSelectorTD[2], 4);
    TextDrawSetProportional(SpawnSelectorTD[2], 1);
    TextDrawSetSelectable(SpawnSelectorTD[2], 1);

    SpawnSelectorTD[3] = TextDrawCreate(399.000, 204.500, "LD_BUM:blkdot");
    TextDrawTextSize(SpawnSelectorTD[3], 100.000, 19.000);
    TextDrawAlignment(SpawnSelectorTD[3], 1);
    TextDrawColor(SpawnSelectorTD[3], 454894591);
    TextDrawSetShadow(SpawnSelectorTD[3], 0);
    TextDrawSetOutline(SpawnSelectorTD[3], 0);
    TextDrawBackgroundColor(SpawnSelectorTD[3], 255);
    TextDrawFont(SpawnSelectorTD[3], 4);
    TextDrawSetProportional(SpawnSelectorTD[3], 1);
    TextDrawSetSelectable(SpawnSelectorTD[3], 1);

    SpawnSelectorTD[4] = TextDrawCreate(399.000, 228.000, "LD_BUM:blkdot");
    TextDrawTextSize(SpawnSelectorTD[4], 100.000, 19.000);
    TextDrawAlignment(SpawnSelectorTD[4], 1);
    TextDrawColor(SpawnSelectorTD[4], 454894591);
    TextDrawSetShadow(SpawnSelectorTD[4], 0);
    TextDrawSetOutline(SpawnSelectorTD[4], 0);
    TextDrawBackgroundColor(SpawnSelectorTD[4], 255);
    TextDrawFont(SpawnSelectorTD[4], 4);
    TextDrawSetProportional(SpawnSelectorTD[4], 1);
    TextDrawSetSelectable(SpawnSelectorTD[4], 1);

    SpawnSelectorTD[5] = TextDrawCreate(449.000, 139.000, "Pilih lokasi spawn");
    TextDrawLetterSize(SpawnSelectorTD[5], 0.188, 0.898);
    TextDrawAlignment(SpawnSelectorTD[5], 2);
    TextDrawColor(SpawnSelectorTD[5], -1);
    TextDrawSetShadow(SpawnSelectorTD[5], 1);
    TextDrawSetOutline(SpawnSelectorTD[5], 1);
    TextDrawBackgroundColor(SpawnSelectorTD[5], 0);
    TextDrawFont(SpawnSelectorTD[5], 1);
    TextDrawSetProportional(SpawnSelectorTD[5], 1);

    SpawnSelectorTD[6] = TextDrawCreate(449.000, 162.500, "Bandara Kota Nexston");
    TextDrawLetterSize(SpawnSelectorTD[6], 0.188, 0.898);
    TextDrawAlignment(SpawnSelectorTD[6], 2);
    TextDrawColor(SpawnSelectorTD[6], -1);
    TextDrawSetShadow(SpawnSelectorTD[6], 1);
    TextDrawSetOutline(SpawnSelectorTD[6], 1);
    TextDrawBackgroundColor(SpawnSelectorTD[6], 0);
    TextDrawFont(SpawnSelectorTD[6], 1);
    TextDrawSetProportional(SpawnSelectorTD[6], 1);

    SpawnSelectorTD[7] = TextDrawCreate(449.000, 186.000, "Pelabuhan Kota Nexston");
    TextDrawLetterSize(SpawnSelectorTD[7], 0.188, 0.898);
    TextDrawAlignment(SpawnSelectorTD[7], 2);
    TextDrawColor(SpawnSelectorTD[7], -1);
    TextDrawSetShadow(SpawnSelectorTD[7], 1);
    TextDrawSetOutline(SpawnSelectorTD[7], 1);
    TextDrawBackgroundColor(SpawnSelectorTD[7], 0);
    TextDrawFont(SpawnSelectorTD[7], 1);
    TextDrawSetProportional(SpawnSelectorTD[7], 1);

    SpawnSelectorTD[8] = TextDrawCreate(449.000, 209.500, "Motel");
    TextDrawLetterSize(SpawnSelectorTD[8], 0.188, 0.898);
    TextDrawAlignment(SpawnSelectorTD[8], 2);
    TextDrawColor(SpawnSelectorTD[8], -1);
    TextDrawSetShadow(SpawnSelectorTD[8], 1);
    TextDrawSetOutline(SpawnSelectorTD[8], 1);
    TextDrawBackgroundColor(SpawnSelectorTD[8], 0);
    TextDrawFont(SpawnSelectorTD[8], 1);
    TextDrawSetProportional(SpawnSelectorTD[8], 1);

    SpawnSelectorTD[9] = TextDrawCreate(449.000, 233.000, "Lokasi Terakhir");
    TextDrawLetterSize(SpawnSelectorTD[9], 0.188, 0.898);
    TextDrawAlignment(SpawnSelectorTD[9], 2);
    TextDrawColor(SpawnSelectorTD[9], -1);
    TextDrawSetShadow(SpawnSelectorTD[9], 1);
    TextDrawSetOutline(SpawnSelectorTD[9], 1);
    TextDrawBackgroundColor(SpawnSelectorTD[9], 0);
    TextDrawFont(SpawnSelectorTD[9], 1);
    TextDrawSetProportional(SpawnSelectorTD[9], 1);
}

/*ShowSpawnSelectorTD(playerid)
{
    HideHBETD(playerid);
    HideRadioVoiceInfoTD(playerid);
	HideServerNameTD(playerid);
    //HideStatsTD(playerid);

    for(new x; x < 10; x++)
    {
        TextDrawShowForPlayer(playerid, SpawnSelectorTD[x]);
    }

    SelectTextDraw(playerid, Y_Nexston);
    SendClientMessage(playerid, Y_SERVER, "(Server) "WHITE"Gunakan "CMDEA"'/cursor' "WHITE"jika mouse hilang dari layar/textdraw tidak bisa ditekan!");
}

HideSpawnSelectorTD(playerid)
{
    for(new x; x < 10; x++)
    {
        TextDrawHideForPlayer(playerid, SpawnSelectorTD[x]);
    }
    
    ShowHBETD(playerid);
	ShowServerNameTD(playerid);
    //ShowStatsTD(playerid);
    ShowRadioVoiceInfoTD(playerid);

    CancelSelectTextDraw(playerid);
}*/